language: python
sudo: false
cache: pip

python:
  - "2.7"

env:
  - DJANGO="django>=1.7,<1.8"

branches:
  only:
    - master

# command to install requirements
install:
  - pip install $DJANGO
  - python setup.py -q develop
  - pip install -r requirements-test.txt

before_script:
  - ./runflake8
  - ./runisort

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source==filemanager runtests.py

# after_success:
#  coveralls
